# SPLASH SCREEN
splashOne = "A"
splash_title_one = "Checking folder structure..."
splash_title_two = "Verifying algorithm dependencies... "
splash_title_three = "Confirming installation of Python Packages..."

# MAIN MENU
mame_one = "AVANTZERO"
mame_two = "Starting..."
mame_three = "v0.2.0"
mame_four = "Project Manager"
mame_five = "Data Generator"
mame_six = "About"
mame_seven = "Credits"
mame_eight = "Exit"
mame_nine = "Experimental Quake III Machinima Algorithm"

# ERRORS
err_one_a_title = "001A"
err_one_a_msg = "Unable to find Python file dependencies:"
err_one_a_link = "TBA" # TODO: ADD DOCS LINK
err_one_b_title = "001B"
err_one_b_msg = "General Exception regarding dependency check:"
err_two_title = "002"
err_two_msg = "Errors with the following packages:"
err_two_link = "TBA" # TODO: ADD DOCS ZELDA
err_four_a_title = "004A"
err_four_a_msg = "AvantZero does not have permission to check/create the folder structure"
err_four_a_link =  "TBA" # TODO: ADD DOCS LINK
err_four_b_title = "004B"
err_four_b_msg = "General Exception regarding the folder structure:"
err_four_b_link = "https://github.com/jiyorude/avantzero/issues"
error_github = "\n\nCheck out the Issues section on GitHub to see whether your issue has been reported."
error_vercel = "\n\nMore info at:"

# PROJECT MANAGER
proj_title_one = "Project Manager"
proj_title_two = "im in your projects, managing stuff"

# DATA GENERATOR
data_title_one = "Data Generator"
data_title_two = "WIP. More things added soon"

# ABOUT
about_title_one = "About AvantZero"
about_title_two = "This section will contain information\nabout the algorithm... Work in progress..."
back_button = "Back"

# CREDITS
credits_title_one = "Credits"
credits_title_two = "This section contains credits information.\nMore coming soon."
